[project]
name = "ragflow-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diagrams>=0.24.3",
    "fastapi>=0.115.11",
    "fastapi-code-generator>=0.5.2",
    "pydantic>=2.10.6",
]
